version: '3.6'

services:
  app:
    image: 'ghcr.io/fullmoonrising/iscoach:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - BOT_USERNAME
      - BOT_TOKEN
      - BOT_PROVIDER_TOKEN
      - BOT_MAIL
      - BOT_MAIL_PASS
      - DB_NAME
      - DB_USER
      - DB_PASS
      - TZ=Europe/Moscow
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    #    ports:
    #      - "5433:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/:rw
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
  nginx:
    image: 'nginx:latest'
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "9876:9876"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf/:ro
      - ./certbot/conf:/etc/letsencrypt/:ro
      - ./certbot/www:/var/www/certbot/:ro
    environment:
      - TZ=Europe/Moscow
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: "certbot/certbot:latest"
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt/:rw
      - ./certbot/www:/var/www/certbot/:rw
    environment:
      - TZ=Europe/Moscow
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: certonly --webroot -w /var/www/certbot --force-renewal --email aravin.roman@yandex.ru --expand -d iscoach.ru --agree-tos
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REPO_USER
      - REPO_PASS
      - TZ=Europe/Moscow
    command: --interval 60 --cleanup --include-restarting app